# This file configures the destination-data-server routing the application's port to the one that should be exposed by the server
version: "2"
services:
  ontouml-server:
    env_file: .env
    build: .
    image: "ontouml-server-${SERVER_NAME}"
    container_name: "ontouml-server-${SERVER_NAME}"
    restart: always
    ports:
      - "${PORT}:${PORT}"
